### ISSUE TITLE
Put 'execute shell' contents to this git

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/jenkins#10]
- We have growing number of jobs.
- Each job has an 'execute shell' section which lists commands, that should be run on the jenkins

I convinced we should put these shell scripts to this git, here are my thoughts:
- Scripts are currently not visible for the community. Hard to understand what is going on. We should be more transparent.
- Multiple jobs for each project should be always in sync. However, we currently rely on people to keep them in sync. Did you know that people make mistakes? Did you know how many jobs are there for openscap base?
- They are not easily accessible. It always takes me time to find them, when I need to know what is tested and what is not. That makes this information source less appealing.
- We don't have history tracked for these scripts. Why are they such and such?
- We cannot have a discussion on changes (pr review) as we are used to for all the other stuff.
- When I have to edit multiple same scripts, I try to make excuses. That means, we need to see major pain, before we start editing these scripts. That causes us to avoid small improvements. That makes us dull. :)

I suggest we have all the execute shell the same:

```
project= # openscap, scap-security-guide, ruby-openscap ...
git clone https://github.com/OpenSCAP/jenkins #or pull
exec bash -x scripts/$project.sh
```

Thoughts?

**Comment by ybznek** [comment]
Good idea. But we need some hierarchy in files. Some jobs use multiple "scripts".

**Comment by ybznek** [comment]
We could use https://wiki.jenkins-ci.org/display/JENKINS/JobConfigHistory+Plugin, too. But git has still some advantages (and disadvantages).

**Comment by mpreisler** [comment]
I have always been against this because it's complicated and frankly we don't do rocket science inside Jenkins. It's mostly running a few steps such as configure, make, make check, make install. I don't think it makes sense to track them in git or publish them for the community.

When we do something complex in a Jenkins job I would rather have it contributed to the tested project. We do something like that with `make jenkins` in SSG.

**Comment by matusmarhefka** [comment]
This is fixed, see `ansible/jobs` directory which contains jobs with shell commands.
