### ISSUE TITLE
[RFE] Allow Jenkins CI job to show result of testing from more than just one slave

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/jenkins#11]
The `scap-security-guide-pull-requests` Jenkins CI job has been configured to run all pull requests checks in parallel on all three of the following systems:
- [el6](https://jenkins.open-scap.org/computer/el6/) to verify OVAL-5.10 content is produced properly (mainly wrt to `make validate` targets),
- [el7](https://jenkins.open-scap.org/computer/el7/) to verify OVAL-5.11 content is produced properly (mainly wrt to `make validate` targets), and
- [fedora23](https://jenkins.open-scap.org/computer/fedora23/) to verify:
  - OVAL-5.11 content is produced properly (mainly wrt to `make validate` targets), but
  - also verify the `ShellCheck` executable won't report some regression on the syntax of provided remediation scripts

The example PR on which all three tests have been performed is the following one:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/pull/1048

The issue is having look at `All checks have passed` section there's only `1 successful check` report, not 3.

Since we need the [scap-security-guide-pull-requests](https://jenkins.open-scap.org/job/scap-security-guide-pull-requests/) jenkins CI job to:
- `pass` only if the specific PR has passed on all three nodes,
- `fail` otherwise,

the `All checks have passed` section should be enhanced to list all three test results.

@ybznek You think this would be possible to implement?

Thanks, Jan.

**Comment by jan-cerny** [comment]
@ybznek Do you think it would be beneficial also for openscap pull requests?

**Comment by ybznek** [comment]
@jan-cerny I don't think so.
We have every week https://jenkins.open-scap.org/job/openscap-maint-RUN-ON-ALL/33/ what test it on all slaves.

We don't have so many pull requests now, and we don't often break something only on one system.

**Comment by mpreisler** [comment]
@ybznek Hasn't this already been implemented?

**Comment by ybznek** [comment]
@mpreisler I think so.

**Comment by iankko** [comment]
Agree. This is available already. Thanks for that, Zbynek! (assuming it has saved us a lot of SSG build process fixes already).
