### ISSUE TITLE
Change Jenkins email "From" address

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/jenkins#12]
Right now it's openscap-maint@redhat.com and redhat.com has SPF records which means the mail will get rejected when arriving to most SMTP servers.

We need to change it to something else.

**Comment by ybznek** [comment]
Any ideas?

**Comment by ybznek** [comment]
Maybe I didn't understand you well. I changed mpreisle@redhat.com to robot@jenkins.openscap.org in jenkins configuration. Is this the same address as you though?

**Comment by mpreisler** [comment]
Yes, I think so. Let's see if I get more bounces, if not I will close this in a few days. Thanks @ybznek!

**Comment by ybznek** [comment]
@mpreisler Do you think we can close it?

**Comment by mpreisler** [comment]
Yes
