### ISSUE TITLE
Out of disk space jenkins

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/jenkins#13]
Free disk space was depleted on one of jenkins slave today.
Classic jobs should not grow in space too much, because we delete old files.

We have 20GB/slave, I think it is enough.

What we need:
- Find what use too much diskspace
- if lots of files rest in /tmp, we need to clean it in someway
  - weekly jenkins job
  - restart machine? (find you if it clean /tmp)
- maybe monitor disk space  - we can add simple check to script what run every week

any tips?

**Comment by ybznek** [comment]
`yum clean all`
helps a lot, about 5GB more after that

**Comment by mpreisler** [comment]
> maybe monitor disk space - we can add simple check to script what run every week

Doesn't Jenkins already do all this? See https://jenkins.open-scap.org/computer/
I agree that we should run `yum clean all` after every `yum update`.

**Comment by ybznek** [comment]
@mpreisler 
- Jenkins show this, but nobody watch it.
- I have added `yum clean all` after `yum update`
