### ISSUE TITLE
Provide test results

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/jenkins#14]
We can provide test result file after every test, so we will able to have nice jenkins-managed stats of tests.

Expected workflow:
1. Run tests over with `| tee "$result"`
2. Transform "$result" to some standardized test result format (.xml/..)
3. Enable job to collect result file
4. Enjoy stats
5. (Maybe more readable results on github)

https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin

**Comment by matusmarhefka** [comment]
This was fixed in master branches by migration to CMake.
