### ISSUE TITLE
The "scap-security-guide-nist-testsuite" Jenkins CI job is still reporting failure (even when it was passing in the past)

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/jenkins#19]
The "scap-security-guide-nist-testsuite" Jenkins CI job is still failing (regardless if the internal testing job passed or not). Have a look at this example:
- https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/140/console

As can be seen there were "0 Errors" detected, but the job was still marked as failing. The corresponding error / warning message was:

```
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed:
No test report files were found. Configuration error?
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE
```

This makes me to think there's some issue with the configuration of the testing job itself, rather than failure in the tests.

P.S.: Right now it's truly failing (example: https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/145/console -- that's a different issue, we will fix in SSG directly). But this report is about the fact, despite of there being 0 Errors, the ssg-nist-testsuite Jenkins CI job is still marked / reported as failing.

**Comment by iankko** [comment]
@ybznek 
Zbynek, could you possibly look / investigate why it's behaving this way?

Thanks, Jan

**Comment by ybznek** [comment]
I have updated expected filename of test results to `summary-rhel*.xml` - to match rhel6 and rhel7 results.. We will see if this change fixed the issue.

Currently it is failing due to real ssg bug. Please, ping me after fix of this bug.

**Comment by iankko** [comment]
@ybznek 

> I have updated expected filename of test results to summary-rhel*.xml - to match rhel6 and rhel7 results.. We will see if this change fixed the issue.

Thanks for that!

> Currently it is failing due to real ssg bug.

Correct. It's this issue (we are already aware of): https://github.com/OpenSCAP/scap-security-guide/issues/1288

> Please, ping me after fix of this bug.

The change from this PR https://github.com/OpenSCAP/scap-security-guide/pull/1295 should fix it. I will ping you once got merged.

Thank you, Jan

**Comment by iankko** [comment]
Checked today. Not completely fixed yet. The SSG issue itself is fixed (got fixed via PR above on Friday).
But the job still fails since RHEL-6 slave was selected for testing and due some reason it re-used scapval-1.2.13.1 version (instead of the most recent scapval-1.2.14.1 one):
  https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/150/consoleFull

I can't look at this right now (need to work on patches for 0.1.30 release). @ybznek Can you hopefully look?

Thanks, Jan

**Comment by ybznek** [comment]
I've rewrited part of code what downloads test suite. I hope, it is already fixed.

**Comment by iankko** [comment]
@ybznek 

> I've rewrited part of code what downloads test suite. I hope, it is already fixed.

Yeah, looks it's [fixed already](https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/161/) -- build from today.

Thanks a lot!

**Comment by iankko** [comment]
And, due to some strange reason it started to fail again. But the issue isn't on SSG side, it fails to locate some directory. See https://jenkins.open-scap.org/job/scap-security-guide-nist-testsuite/162/ and the subsequent one.

Re-opening.

**Comment by yuumasato** [comment]
There is no way to check the build 162 from scap-security-guide-nist-testsuite, it doesn't exist anymore.
Some effort has been done to fix this jenkins job in https://github.com/OpenSCAP/scap-security-guide/issues/1344 and as of today, the latest 4 runs were successful.

I think we can close this issue.
