### ISSUE TITLE
TLS certificate from letsencrypt

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/jenkins#2]
Currently we use a self-signed AND relatively weak TLS cert, we should move to TLS 1.2 letsencrypt certificate that is trusted by browsers.

As part of the letsencrypt beta program I have whitelisted jenkins.open-scap.org. It needs coordination with somebody who knows the infrastructure to deploy it though.

**Comment by mpreisler** [comment]
I am able to get the certificates now. All I need is jenkins to host a few plain text files over HTTP. Can we coordinate to get this done @ybznek ?

**Comment by ybznek** [comment]
Done.
