### ISSUE TITLE
Test `./configure --disable-probes`

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/jenkins#20]
We need `./configure --disable-probes` to work for SCAP Workbench binary builds for Windows and OSX. This is only tested when I build SCAP Workbench and we often break this scenario.

Please add this configuration in Jenkins so that we continuously test it.

**Comment by ybznek** [comment]
I've added https://jenkins.open-scap.org/job/openscap-master-disabled-probes/ - clonned `openscap-master`, but with --disable-probes.

@mpreisler Is it enough for master, or do you want it rather for maint-*?
IMHO best solution test only master and (make/keep) master green.

**Comment by mpreisler** [comment]
> @mpreisler Is it enough for master, or do you want it rather for maint-*?
> IMHO best solution test only master and (make/keep) master green.

agreed

**Comment by mpreisler** [comment]
This has been implemented.
