### ISSUE TITLE
Add Fedora 24 node

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/jenkins#21]
Fedora 24 was released on June 21st. We need to set up Fedora 24 virtual machine, add it to Jenkins and use it for builds and tests on Jenkins.

**Comment by iankko** [comment]
Nice catch, Jan!

While on this we can schedule decommission of F22 one on 2016-07-19 IIRC:
- https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/4FBGGXFXRMU5GHT6OSSNOYVPMONZDWSD/

**Comment by ybznek** [comment]
Fedora24 should be ready. I leave this opened due to fedora22 decommission.

**Comment by jan-cerny** [comment]
We can decommission F22 that now.

**Comment by ybznek** [comment]
I have deleted f22 slave from jenkins.
