### ISSUE TITLE
Remove Fedora 23 node

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/jenkins#27]
Fedora 23 EOL was on December 20th, 2016
We waste resources by keeping it on.

**Comment by dahaic** [comment]
I have removed F23 node from the pool.

**Comment by mpreisler** [comment]
This has broken scap security guide pull requests.

```
Configuration scap-security-guide-pull-requests » node-fedora23 is still in the queue: fedora23 is offline
```

None of the automated PR checks will go through.

**Comment by mpreisler** [comment]
I have used https://jenkins.open-scap.org/label/node-fedora23/ to remove Fedora23 from all the tasks.

**Comment by mpreisler** [comment]
I think I have fixed it. Please remove Fedora23 from Jenkins master before closing this ticket.

**Comment by mpreisler** [comment]
.....
