### ISSUE TITLE
A PR is pointing to wrong check in jenkins

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/jenkins#30]
Jenkins test link in https://github.com/OpenSCAP/scap-workbench/pull/113 is pointing to wrong run of checks.

While it points to https://jenkins.open-scap.org/job/scap-workbench-pull-requests/1/ it should point to https://jenkins.open-scap.org/job/scap-workbench-pull-requests/38/

**Comment by mpreisler** [comment]
I assume this has been fixed?

**Comment by yuumasato** [comment]
No, it hasn't. And we probably cannot fix it anymore.
It happend during @openscap-jenkins watch, and very likely in past instance of jenkins.
The https://jenkins.open-scap.org/job/scap-workbench-pull-requests/38/ job doesn't exist in current instance of jenkins. In current jenkins, latest job for scap-workbench-pull-request is 32.

Sorry for closing without explanation.
