### ISSUE TITLE
Build failures in OpenSCAP maint

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/jenkins#33]
https://jenkins.open-scap.org/job/openscap-maint/10/

Build and test itself looks OK, it successfullly creates the "dist tarball", but then it fails:

```
Cannot find config with Id [org.jenkinsci.plugins.managedscripts.ScriptConfig1445854237346]. Are you sure it exists? Please check the configuration.
Build step 'Execute managed script' marked build as failure
Sending e-mails to: openscap-maint@redhat.com
Finished: FAILURE
```

**Comment by matusmarhefka** [comment]
@jan-cerny Fixed in https://jenkins.open-scap.org/job/openscap-maint/11/

The error was in jenkins configuration for openscap-maint job. After build there was another empty build step which should execute script, but no script was specified. I removed this empty build step.
