### ISSUE TITLE
release-testing-run-all clogs the system

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/jenkins#4]
2 of these jobs have been running for several days. They are endangering the stability of the system because they clog some of the slaves.

If the job really takes this long we probably should decide to run it in parts.

Could we investigate this? Maybe we can disable this job for the time being?

**Comment by ybznek** [comment]
I don't know If it need some investigation. These jobs was waiting for fedora23 which has been mark as offline due to ssg issue. This was rare situation. I think was not "stealing" any performance while it is waiting.

I think, that no action is required for now. Or do you think something else?
