### ISSUE TITLE
SSG pull requests are tested serially and only on RHEL6

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/jenkins#5]
The task has a label `rhel6`, this means it can only be tested on one of the slaves.

Is this what we want? That means that we are never testing `oval 5.11` in jenkins.

**Comment by mpreisler** [comment]
![image](https://cloud.githubusercontent.com/assets/753153/11694309/ac0dd5be-9ea9-11e5-85f6-87e4f5913964.png)

Normally this wouldn't be a big deal but especially today it's slowing down SSG development. And it was even worse a couple hours ago.

Could we open the task for all slaves or is there a reason why RHEL6 must be used? If we really need RHEL6, could we build multiple tasks in parallel?

**Comment by ybznek** [comment]
I don't remember that I have done it. I don't know any reason to limit it only for rhel6.
@iankko  Do you remember any reason?

**Comment by ybznek** [comment]
There are now too long queue, I have decided to remove limit to rhel6, I hope that I haven't broke something.

**Comment by iankko** [comment]
@ybznek 

> There are now too long queue, I have decided to remove limit to rhel6, I hope that I haven't broke something.

Thanks! (ad breaking something - didn't look. But even if we would, we should fix those issues rather than limit the testing just for RHEL-6). This is great move in any case.

**Comment by mpreisler** [comment]
It seems the restriction to just RHEL6 has been lifted but still only one PR is tested at a time! This can be very frustrating, especially close to a release. I am not aware of any side effects of the PR test, so why are we building it just once at a time?

![image](https://cloud.githubusercontent.com/assets/753153/11743918/b7b1fc34-a00b-11e5-814e-1691fcd7bdd2.png)

**Comment by mpreisler** [comment]
The same thing happens with the `scap-security-guide` job that tests the master branch. It will only execute one job at a time. I have no idea why and I see no reason why it can't be building multiple times even on the same slave.

**Comment by mpreisler** [comment]
I have enabled concurrent builds on both the jobs. Let's see what it does.

**Comment by mpreisler** [comment]
I can confirm that the `scap-security-guide` job has full isolation and workspaces are separate.

e.g.:

```
Building remotely on fedora22 (fedora node-fedora22) in workspace /home/jenkins/workspace/scap-security-guide@2
```

The suffix increases as more and more builds are scheduled. The builds haven't finished yet so I am not sure whether they will succeed.

**Comment by mpreisler** [comment]
Same thing with the pull request job. I will leave this open to learn why we disabled the concurrent builds, perhaps I am missing something. Other than that it seems I solved the problem.

**Comment by isimluk** [comment]
It seems to me this is now fixed. If not, @mpreisler can you please update the name of this issue?
