### ISSUE TITLE
"scap-security-guide" SSG CI Jenkins job now returns "java.io.IOException: remote file operation failed" result on Fedora22 and Fedora23 slaves (rather than performing testing of the actual SSG pull request that got merged)

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/jenkins#8]
AFAICT this behaviour started after most recent Jenkins upgrade last Thursday (2016-01-21) IIRC:
- &nbsp; &nbsp; [1] https://jenkins.open-scap.org/job/scap-security-guide/505/console
- &nbsp; &nbsp; [2] https://jenkins.open-scap.org/job/scap-security-guide/506/console
- &nbsp; &nbsp; [3] https://jenkins.open-scap.org/job/scap-security-guide/507/console
## Current result:

IOW rather the `scap-security-guide` to perform the testing of the particular / underlying PR that got merged, it returns some Jenkins CI error:

```
java.io.IOException: remote file operation failed: /home/jenkins/workspace/scap-security-guide at hudson.remoting.Channel@3af655b6:fedora23: java.io.IOException: Remote call on fedora23 failed
..
Caused by: java.io.IOException: Remote call on fedora23 failed
..
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy8
```
## Expected result:

Underlying merged PR is tested.
## Additional information:

So far this behaviour has been noticed / seems to be to "scap-security-guide" Jenkins SSG CI job specific (other openscap Jenkins CI jobs seem to be actually testing what's desired AFAICT). Also so far this behaviour has been noticed on the following two Jenkins slaves:
- Fedora22
- Fedora23

Thanks, Jan.

**Comment by jan-cerny** [comment]
The strange thing is that Jenkins does not work for SSG pull requests, but it works for OpenSCAP pull requests, today eg https://jenkins.open-scap.org/job/openscap-pull-requests/324/console

**Comment by mpreisler** [comment]
I believe this has been fixed by me rebooting the Fedora slaves, see https://jenkins.open-scap.org/job/scap-security-guide/509/

Please reopen if you still have issues.

**Comment by iankko** [comment]
Brilliant. Thanks Martin!
